#############################################################################
# Makefile for building: pg_query_analyser
# Generated by qmake (2.01a) (Qt 4.7.1) on: Fri Feb 4 02:40:13 2011
# Project:  pg_query_analyser.pro
# Template: app
# Command: /usr/local/bin/qmake-qt4 -o Makefile pg_query_analyser.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I../../../local/share/qt4/mkspecs/freebsd-g++ -I. -I../../../local/include/qt4/QtCore -I../../../local/include/qt4/QtSql -I../../../local/include/qt4 -I. -I../../../local/include
LINK          = g++
LFLAGS        = -Wl,-O1 -pthread -Wl,-rpath,/usr/local/lib/qt4
LIBS          = $(SUBLIBS)  -L/usr/local/lib -L/usr/local/lib/qt4 -lQtSql -L/usr/local/lib/qt4 -L/usr/local/lib -lQtCore 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		query.cpp \
		arg.cpp \
		args.cpp \
		queries.cpp 
OBJECTS       = main.o \
		query.o \
		arg.o \
		args.o \
		queries.o
DIST          = ../../../local/share/qt4/mkspecs/common/g++.conf \
		../../../local/share/qt4/mkspecs/common/unix.conf \
		../../../local/share/qt4/mkspecs/qconfig.pri \
		../../../local/share/qt4/mkspecs/features/qt_functions.prf \
		../../../local/share/qt4/mkspecs/features/qt_config.prf \
		../../../local/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../local/share/qt4/mkspecs/features/default_pre.prf \
		../../../local/share/qt4/mkspecs/features/release.prf \
		../../../local/share/qt4/mkspecs/features/default_post.prf \
		../../../local/share/qt4/mkspecs/features/unix/thread.prf \
		../../../local/share/qt4/mkspecs/features/warn_on.prf \
		../../../local/share/qt4/mkspecs/features/qt.prf \
		../../../local/share/qt4/mkspecs/features/moc.prf \
		../../../local/share/qt4/mkspecs/features/resources.prf \
		../../../local/share/qt4/mkspecs/features/uic.prf \
		../../../local/share/qt4/mkspecs/features/yacc.prf \
		../../../local/share/qt4/mkspecs/features/lex.prf \
		../../../local/share/qt4/mkspecs/features/include_source_dir.prf \
		pg_query_analyser.pro
QMAKE_TARGET  = pg_query_analyser
DESTDIR       = 
TARGET        = pg_query_analyser

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pg_query_analyser.pro  ../../../local/share/qt4/mkspecs/freebsd-g++/qmake.conf ../../../local/share/qt4/mkspecs/common/g++.conf \
		../../../local/share/qt4/mkspecs/common/unix.conf \
		../../../local/share/qt4/mkspecs/qconfig.pri \
		../../../local/share/qt4/mkspecs/features/qt_functions.prf \
		../../../local/share/qt4/mkspecs/features/qt_config.prf \
		../../../local/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../local/share/qt4/mkspecs/features/default_pre.prf \
		../../../local/share/qt4/mkspecs/features/release.prf \
		../../../local/share/qt4/mkspecs/features/default_post.prf \
		../../../local/share/qt4/mkspecs/features/unix/thread.prf \
		../../../local/share/qt4/mkspecs/features/warn_on.prf \
		../../../local/share/qt4/mkspecs/features/qt.prf \
		../../../local/share/qt4/mkspecs/features/moc.prf \
		../../../local/share/qt4/mkspecs/features/resources.prf \
		../../../local/share/qt4/mkspecs/features/uic.prf \
		../../../local/share/qt4/mkspecs/features/yacc.prf \
		../../../local/share/qt4/mkspecs/features/lex.prf \
		../../../local/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/local/lib/qt4/libQtSql.prl \
		/usr/local/lib/qt4/libQtCore.prl
	$(QMAKE) -o Makefile pg_query_analyser.pro
../../../local/share/qt4/mkspecs/common/g++.conf:
../../../local/share/qt4/mkspecs/common/unix.conf:
../../../local/share/qt4/mkspecs/qconfig.pri:
../../../local/share/qt4/mkspecs/features/qt_functions.prf:
../../../local/share/qt4/mkspecs/features/qt_config.prf:
../../../local/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../local/share/qt4/mkspecs/features/default_pre.prf:
../../../local/share/qt4/mkspecs/features/release.prf:
../../../local/share/qt4/mkspecs/features/default_post.prf:
../../../local/share/qt4/mkspecs/features/unix/thread.prf:
../../../local/share/qt4/mkspecs/features/warn_on.prf:
../../../local/share/qt4/mkspecs/features/qt.prf:
../../../local/share/qt4/mkspecs/features/moc.prf:
../../../local/share/qt4/mkspecs/features/resources.prf:
../../../local/share/qt4/mkspecs/features/uic.prf:
../../../local/share/qt4/mkspecs/features/yacc.prf:
../../../local/share/qt4/mkspecs/features/lex.prf:
../../../local/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/local/lib/qt4/libQtSql.prl:
/usr/local/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile pg_query_analyser.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pg_query_analyser1.0.0 || $(MKDIR) .tmp/pg_query_analyser1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pg_query_analyser1.0.0/ && $(COPY_FILE) --parents query.h main.h args.h arg.h queries.h .tmp/pg_query_analyser1.0.0/ && $(COPY_FILE) --parents main.cpp query.cpp arg.cpp args.cpp queries.cpp .tmp/pg_query_analyser1.0.0/ && (cd `dirname .tmp/pg_query_analyser1.0.0` && $(TAR) pg_query_analyser1.0.0.tar pg_query_analyser1.0.0 && $(COMPRESS) pg_query_analyser1.0.0.tar) && $(MOVE) `dirname .tmp/pg_query_analyser1.0.0`/pg_query_analyser1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pg_query_analyser1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp main.h \
		query.h \
		args.h \
		arg.h \
		queries.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

query.o: query.cpp query.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o query.o query.cpp

arg.o: arg.cpp arg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o arg.o arg.cpp

args.o: args.cpp args.h \
		arg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o args.o args.cpp

queries.o: queries.cpp queries.h \
		query.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queries.o queries.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

